[install]
peer = true
production = false
frozen-lockfile = false
registry = "https://registry.npmjs.org"

[install.scopes]
next = "https://registry.npmjs.org"

[build]
target = "browser"
minify = true
sourcemap = true
framework = "next"

[runtime]
env = "development"
watch = true
